version: '3.8'

services:
  # Main application for testing
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - FLASK_ENV=testing
      - FLASK_DEBUG=False
      - PORT=8080
      - FIRESTORE_EMULATOR_HOST=firestore-emulator:8081
      - GCP_PROJECT_ID=test-project
      - WEBHOOK_SECRET=test_webhook_secret_123
      - TESTING=true
      - INTEGRATION_TEST_MODE=true
    depends_on:
      - firestore-emulator
    networks:
      - test-network

  # Integration test runner
  test-runner:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      - FLASK_ENV=testing
      - TESTING=true
      - INTEGRATION_TEST_MODE=true
      - APP_URL=http://app:8080
      - FIRESTORE_EMULATOR_HOST=firestore-emulator:8081
      - GCP_PROJECT_ID=test-project
    depends_on:
      - app
      - firestore-emulator
    volumes:
      - .:/app/src
      - ./test-results:/app/test-results
    working_dir: /app/src
    networks:
      - test-network
    command: >
      sh -c "
        echo 'Waiting for services to be ready...' &&
        sleep 10 &&
        echo 'Running integration tests...' &&
        python -m pytest tests/test_integration_docker.py -v --tb=short --junitxml=/app/test-results/junit.xml --html=/app/test-results/report.html --self-contained-html
      "

  # Google Cloud Firestore Emulator (ONLY service actually needed)
  firestore-emulator:
    image: gcr.io/google.com/cloudsdktool/cloud-sdk:latest
    platform: linux/amd64  # Force AMD64 platform for compatibility
    environment:
      - FIRESTORE_PROJECT_ID=test-project
    networks:
      - test-network
    ports:
      - "8081:8081"  # Expose port for debugging
    command: >
      sh -c "
        apt-get update &&
        apt-get install -y google-cloud-cli-firestore-emulator &&
        gcloud beta emulators firestore start --host-port=0.0.0.0:8081 --project=test-project --rules=/dev/null
      "
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

networks:
  test-network:
    driver: bridge
