version: '3.8'

services:
  # Main application for testing (with mocked Firestore)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - FLASK_ENV=testing
      - FLASK_DEBUG=False
      - PORT=8080
      - GCP_PROJECT_ID=test-project
      - WEBHOOK_SECRET=test_webhook_secret_123
      - TESTING=true
      - INTEGRATION_TEST_MODE=true
      # Mock the Firestore connection by not setting FIRESTORE_EMULATOR_HOST
    ports:
      - "8080:8080"  # Expose for testing
    networks:
      - test-network

  # Integration test runner (runs against the app)
  test-runner:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      - FLASK_ENV=testing
      - TESTING=true
      - INTEGRATION_TEST_MODE=true
      - APP_URL=http://app:8080
      - GCP_PROJECT_ID=test-project
    depends_on:
      - app
    volumes:
      - .:/app/src
      - ./test-results:/app/test-results
    working_dir: /app/src
    networks:
      - test-network
    command: >
      sh -c "
        echo 'Waiting for services to be ready...' &&
        sleep 10 &&
        echo 'Running integration tests...' &&
        python -m pytest tests/test_integration_docker.py -v --tb=short --junitxml=/app/test-results/junit.xml --html=/app/test-results/report.html --self-contained-html
      "

networks:
  test-network:
    driver: bridge
