services:
  # Main application service
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - TESTING=true
      - GCP_PROJECT_ID=test-project
      - WEBHOOK_SECRET=test_webhook_secret_123
      - FIRESTORE_EMULATOR_HOST=firestore-emulator:8080
    networks:
      - test-network
    depends_on:
      firestore-emulator:
        condition: service_healthy

  # Firestore emulator for database testing
  firestore-emulator:
    image: gcr.io/google.com/cloudsdktool/cloud-sdk:alpine
    command: >
      sh -c "gcloud components install cloud-firestore-emulator --quiet &&
             gcloud beta emulators firestore start --host-port=0.0.0.0:8080"
    ports:
      - "8081:8080"
    environment:
      - CLOUDSDK_CORE_PROJECT=test-project
    networks:
      - test-network
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8080"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Test runner service
  test-runner:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - ./tests:/app/tests
      - ./test-results:/app/test-results
    environment:
      - APP_URL=http://app:8080
      - FIRESTORE_EMULATOR_HOST=firestore-emulator:8080
    networks:
      - test-network
    depends_on:
      app:
        condition: service_healthy
      firestore-emulator:
        condition: service_healthy

networks:
  test-network:
    driver: bridge 