# ⚡ Fast Docker Test Configuration for TelegramGroupie
# Optimized for speed: No Firestore emulator needed in TESTING=true mode

services:
  # Main application service
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - TESTING=true
      - GCP_PROJECT_ID=test-project
      - WEBHOOK_SECRET=test_webhook_secret_123
    networks:
      - test-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthz"]
      interval: 3s
      timeout: 2s
      retries: 5
      start_period: 5s

  # Test runner service
  test-runner:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - ./tests:/app/tests
      - ./test-results:/app/test-results
    environment:
      - APP_URL=http://app:8080
    networks:
      - test-network
    depends_on:
      app:
        condition: service_healthy

networks:
  test-network:
    driver: bridge
