name: 🔍 Static Code Analysis

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  PYTHON_VERSION: '3.11'

jobs:
  # ==============================================
  # Ruff - Primary Linting and Formatting
  # ==============================================
  ruff-analysis:
    name: ⚡ Ruff Analysis
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install Ruff
      run: |
        python -m pip install --upgrade pip
        pip install ruff

    - name: Run Ruff linter
      run: |
        echo "🔍 Running Ruff linter..."
        ruff check . --output-format=github

    - name: Run Ruff formatter check
      run: |
        echo "🎨 Checking code formatting..."
        ruff format --check .

    - name: Generate Ruff report
      if: always()
      run: |
        echo "📄 Generating Ruff report..."
        ruff check . --output-format=json > ruff-report.json

    - name: Upload Ruff report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: ruff-report
        path: ruff-report.json

  # ==============================================
  # Security Scanning
  # ==============================================
  security-scan:
    name: 🛡️ Security Scan
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install security tools
      run: |
        python -m pip install --upgrade pip
        pip install bandit[toml]

    - name: Run Bandit security scan
      run: |
        echo "🔒 Running security scan..."
        bandit -r . -f json -o bandit-report.json --exclude ./venv,./tests || true

    - name: Upload security report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: security-report
        path: bandit-report.json

  # ==============================================
  # Quality Gate
  # ==============================================
  quality-gate:
    name: 🎯 Quality Gate
    runs-on: ubuntu-latest
    needs: [ruff-analysis, security-scan]
    if: always()
    
    steps:
    - name: Check quality status
      run: |
        echo "=== Quality Gate Results ==="
        echo "🔍 Ruff Analysis: ${{ needs.ruff-analysis.result }}"
        echo "🛡️ Security Scan: ${{ needs.security-scan.result }}"
        
        # Ruff must pass for code quality
        if [[ "${{ needs.ruff-analysis.result }}" != "success" ]]; then
          echo "❌ Quality gate failed: Ruff analysis issues detected"
          echo "Please fix linting/formatting issues and try again"
          exit 1
        fi
        
        # Security scan can warn but not fail the build
        if [[ "${{ needs.security-scan.result }}" != "success" ]]; then
          echo "⚠️ Security scan had issues - please review"
        fi
        
        echo "✅ Quality gate passed!"

  # ==============================================
  # Summary Report
  # ==============================================
  analysis-summary:
    name: 📋 Analysis Summary
    runs-on: ubuntu-latest
    needs: [ruff-analysis, security-scan]
    if: always()
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download reports
      uses: actions/download-artifact@v4
      with:
        path: ./reports
      continue-on-error: true
    
    - name: Generate summary
      run: |
        echo "# 🔍 Static Analysis Summary" > analysis-summary.md
        echo "" >> analysis-summary.md
        echo "**Branch:** ${{ github.ref_name }}" >> analysis-summary.md
        echo "**Commit:** ${{ github.sha }}" >> analysis-summary.md
        echo "**Date:** $(date)" >> analysis-summary.md
        echo "" >> analysis-summary.md
        echo "## Results" >> analysis-summary.md
        echo "" >> analysis-summary.md
        echo "| Tool | Status | Notes |" >> analysis-summary.md
        echo "|------|--------|-------|" >> analysis-summary.md
        echo "| Ruff Linter | ${{ needs.ruff-analysis.result }} | Code quality and formatting |" >> analysis-summary.md
        echo "| Security Scan | ${{ needs.security-scan.result }} | Security vulnerability check |" >> analysis-summary.md
        echo "" >> analysis-summary.md
        
        # Count Python files
        py_files=$(find . -name "*.py" -not -path "./venv/*" -not -path "./.git/*" | wc -l)
        echo "**Files analyzed:** $py_files Python files" >> analysis-summary.md
        
        # Show overall status
        if [[ "${{ needs.ruff-analysis.result }}" == "success" ]]; then
          echo "" >> analysis-summary.md
          echo "✅ **Overall Status: PASSED**" >> analysis-summary.md
        else
          echo "" >> analysis-summary.md
          echo "❌ **Overall Status: FAILED**" >> analysis-summary.md
        fi
    
    - name: Upload summary
      uses: actions/upload-artifact@v4
      with:
        name: analysis-summary
        path: analysis-summary.md
