name: Quality Report
on:
  workflow_run:
    workflows: ["Static Analysis"]
    types:
      - completed
jobs:
  quality-report:
    runs-on: ubuntu-latest
    steps:
      - name: Download coverage report
        uses: actions/download-artifact@v4
        with:
          name: coverage-report
      - name: Download Bandit report
        uses: actions/download-artifact@v4
        with:
          name: bandit-report 